# -*- coding: utf-8 -*-
"""YT_chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFkz2GRZqSTsEMvP3ftxYKxO-g3a2mia
"""

import os
os.environ["HUGGINGFACEHUB_API_TOKEN"]="xxx"

!pip install -q youtube-transcript-api langchain-community langchain-huggingface faiss-cpu tiktoken python-dotenv

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled

from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_huggingface import HuggingFaceEmbeddings, HuggingFaceEndpoint , ChatHuggingFace

from langchain_community.vectorstores import FAISS

from langchain_core.prompts import PromptTemplate

from langchain_core.documents import Document

from huggingface_hub import InferenceClient

client = InferenceClient()

"""indexing

"""

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled

video_id = "PUfADhkq1LI"
try:
    api = YouTubeTranscriptApi()
    transcript_list = api.fetch(video_id, languages=["en", "hi"])

    transcript = " ".join(chunk.text for chunk in transcript_list)

    print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video.")

transcript

"""text_splitting"""

splitter=RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100,
    length_function=len
)

#spliting transcript and converting it into a list of  document object
chunks=splitter.create_documents([transcript])

#vectore store creatoin
from langchain_community.vectorstores import FAISS

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

vector_store = FAISS.from_documents(
    chunks,
    embeddings
)

#all documents  converted to vector and added to vectore store
vector_store.add_documents(chunks)

"""CREATING CONTEXT

"""

chat_history=[]

query="why we need this"

context_query = PromptTemplate(
    template="""
Rewrite the given query into a clear and detailed search query
that will help retrieve all relevant information from the vector store.

Query: {query}

Search query:
""",
    input_variables=["query"]
)
search_query = context_query.format(query=query)

retriever=vector_store.as_retriever(search_kwargs={"k": 6})

context = retriever.invoke(search_query)

"""prompt for llm"""

template = PromptTemplate(
    template = """You are a helpful assistant.
    Answer the user's question using ONLY the provided context and chat history.
    first understand the context of history till now and then answer the question according to the requrements .
    Do not simply copy or repeat the context. Understand it and give a clear,
    direct answer to the question.
    If the context does not contain enough information to answer, say "I don't know."

    Context:
    {context}
    chat history:
    {chat_history}
    Question:
    {query}

    Answer:
    """,
    input_variables=["context", "query","chat_history"]
)
prompt = template.invoke({'query':'query','context':'context','chat_history':'chat_history'})

from huggingface_hub import InferenceClient
from langchain_core.runnables import RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def call_llm(prompt):
    response = client.chat.completions.create(
        model="meta-llama/Llama-3.1-8B-Instruct",
        messages=[
            {
                "role": "user",
                "content": prompt.to_string()
            }
        ],
        max_tokens=512,
        temperature=0.7
    )

    return response.choices[0].message.content

model = RunnableLambda(call_llm)

parser = StrOutputParser()

result = template | model | parser

def ask_question(query):
    search_query = context_query.format(query=query)

    docs = retriever.invoke(search_query)

    answer = result.invoke({
        "context": docs,
        "query": query,
        "chat_history": chat_history
    })

    chat_history.append({
        "query": query,
        "answer": answer
    })

    return answer





